# Generated by Django 5.2.6 on 2025-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_filmlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlar',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='filmlar',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
